POST http://localhost:3008/api/blogs

Content-Type: application/json

{
  "title": "Understanding REST Client",
  "author": "John DODDododidi",
  "url": "http://example.com",
  "likes": 10,
  "userId": "675efee9459bf1b97670514c" 
}